title: TLD Squatting
description: >- # 
  List of companies that have squatted on entire TLDs.
baseurl: "/tld-squatting"
url: "https://captnemo.in" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  captn3m0

theme: minima

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - "*.py"
  - vendor
author:
  name: Nemo
sass:
  sass_dir: _scss
  quiet_deps: true

rtypes:
  - unrestricted
  - semi-unrestricted